name: Main_Workflows

on:
  push:
    branches:
      - main

#job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "test"
      #  uses: actions/checkout@v3

  #    - name: Run tests
  #      run: npm test
