#워크 플로우 이름
name: Main_Workflows

#워크 플로우 특징 정의
on:
  push:
    branches:
      - main

#job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."
